checkpoints:
  checkpoint_interval: 5000
  checkpoints_path: checkpoints_pleias_360m
  checkpoints_path_is_shared_file_system: false
  resume_checkpoint_path: checkpoints_pleias_360m
  save_initial_state: false
data_stages:
- data:
    dataset:
      dataset_folder: annealing_corpus
    num_loading_workers: 24
    seed: 42
  name: Annealing Corpus
  start_training_step: 1
- data:
    dataset:
      dataset_folder: instruct_rag_corpus
    num_loading_workers: 24
    seed: 42
  name: Instruct+RAG Corpus
  start_training_step: 518001
general:
  benchmark_csv_path: null
  consumed_train_samples: null
  ignore_sanity_checks: true
  project: pretrain
  run: pleias_360m_train_%date_%jobid
  seed: 42
  step: null
lighteval: null
logging:
  iteration_step_info_interval: 1
  log_level: info
  log_level_replica: info
model:
  ddp_bucket_cap_mb: 25
  dtype: bfloat16
  init_method:
    std: 0.025
  make_vocab_size_divisible_by: 1
  model_config:
    bos_token_id: 1
    eos_token_id: 2
    hidden_act: silu
    hidden_size: 1024
    initializer_range: 0.02
    intermediate_size: 2560
    is_llama_config: true
    max_position_embeddings: 2048
    num_attention_heads: 16
    num_hidden_layers: 26
    num_key_value_heads: 8
    pad_token_id: null
    pretraining_tp: 1
    rms_norm_eps: 1.0e-05
    rope_scaling: null
    tie_word_embeddings: true
    use_cache: true
    vocab_size: 65536
    rope_theta: 10000
optimizer:
  accumulate_grad_in_fp32: true
  clip_grad: 1.0
  learning_rate_scheduler:
    learning_rate: 0.003
    lr_decay_starting_step: 30001
    lr_decay_steps: 468000
    lr_decay_style: cosine
    lr_warmup_steps: 30000
    lr_warmup_style: linear
    min_decay_lr: 0.000006
  optimizer_factory:
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-08
    name: adamW
    torch_adam_is_fused: true
  weight_decay: 0.01
  zero_stage: 0
parallelism:
  recompute_layer: false
  dp: 16  # 64 before instruct + rag
  expert_parallel_size: 1
  pp: 1
  pp_engine: 1f1b
  tp: 1
  tp_linear_async_communication: false
  tp_mode: ALL_REDUCE
profiler: null
tokenizer:
  tokenizer_max_length: null
  tokenizer_name_or_path: pleias_tokenizer
  tokenizer_revision: null
tokens:
  batch_accumulation_per_replica: 2
  limit_test_batches: 0
  limit_val_batches: 0
  micro_batch_size: 8
  sequence_length: 2048
  train_steps: 800000
  val_check_interval: -1
